-- Which product type has generated the highest total revenue?
select ProductType, sum(Revenue)as Revenue from supply 
group by 1 
order by 2 desc 
limit 1 ;

-- Which supplier has the highest average defect rate across all products?
select SupplierName, round(avg(DefectRate),2)as Average_Defect_Rate from supply
group by 1 
order by 2 desc 
limit 1 ;

-- What is the total manufacturing cost incurred by each supplier?
select SupplierName , round(sum(ManufacturingCost),2)as Manufacturing_Cost 
from supply 
group by 1 order by 1 ;

-- Which shipping carrier has the lowest average shipping cost?
select ShippingCarrier , round(avg(ShippingCost),2)as Average_Shipping_Cost
from supply 
group by 1 
order by 2 
limit 1 ;

-- What is the total revenue generated by each transportation mode?
select TransportMode, round(sum(Revenue),2)as Revenue
from supply 
group by 1 ;

-- Which city (supplier location) has the highest total production volume?
select Supplierlocation , sum(ProductionVolume)as Production_Volume
from supply 
group by 1 
order by 2 desc 
limit 1 ;

-- What is the average shipping time for each shipping carrier?
select ShippingCarrier, round(avg(ShippingTime),2) as Shipping_Time 
from supply 
group by 1 
order by 1 ;

-- Which product type has the highest average manufacturing cost?
select ProductType, round(avg(ManufacturingCost),2)as Manufacturing_Cost 
from supply 
group by 1 
order by 2 desc
limit 1 ;

-- Which supplier has the lowest average lead time?
select SupplierName , round(avg(SupplierLeadTime),2) as Lead_Time 
from supply 
group by 1 
order by 2 
limit 1 ;

-- What is the total shipping cost incurred for each route?
select Route, round(sum(ShippingCost),2)as Shipping_Cost
from supply 
group by 1
order by 1 ;

-- What is the average manufacturing lead time for each product type?
select ProductType, round(avg(ManufacturingLeadTime),2)as Manufacturing_Lead_Time
from supply 
group by 1 ;

-- Which transportation mode has the highest total transportation cost?
select TransportMode, round(sum(TransportCost),2)as Transportation_Cost
from supply 
group by 1
order by 2 desc 
limit 1 ; 

-- Which product SKU has the highest defect rate?
select SKU, DefectRate 
from supply
where DefectRate = (select max(DefectRate) from supply);

-- What is the average order quantity for each product type?
select ProductType, avg(OrderQuantity)as average_order_quantity
from supply
group by 1 ; 

-- Which supplier has the highest total revenue contribution?
select SupplierName, round(sum(Revenue),2)as Revenue
from supply 
group by 1 
order by 2 desc
limit 1;

-- What is the average defect rate for each product type?
select ProductType, round(avg(DefectRate),2)as Defect_rate 
from supply 
group by 1;

-- Which shipping carrier has handled the most orders (has the highest record count)?
select ShippingCarrier, count(*)as Number_of_orders 
from supply 
group by 1
order by 2 desc 
limit 1;

-- What is the total number of products sold by each supplier?
select SupplierName, sum(UnitsSold)as Number_of_products_sold
from supply
group by 1 
order by 1 ;

-- Which city (supplier location) has the lowest average manufacturing cost?
select SupplierLocation as City, round(avg(ManufacturingCost),2)as Manufacturing_Cost
from supply
group by 1 
order by 2 
limit 1 ;

-- What is the average lead time for each supplier location?
select SupplierLocation, round(avg(SupplierLeadTime),2)as Average_supplier_lead_time
from supply 
group by 1;